### ISSUE TITLE
View location

### ISSUE THREAD

**Issue by PeterNewsham** [BVNetwork/InstantArticles#1]
I'm currently getting the follow exception as the view cannot be found:

"The view '/modules/BVNetwork.InstantArticles/Views/RssPage/Index.cshtml' or its master was not found or no view engine supports the searched locations. The following locations were searched:
/modules/BVNetwork.InstantArticles/Views/RssPage/Index.cshtml"

I believe this is being caused by a typo in InstantArticleRssPageController.cs

`var viewResult = View(Paths.PublicRootPath + "BVNetwork.InstantArticles/Views/RssPage/Index.cshtml", model);`

Which should be:
`var viewResult = View(Paths.PublicRootPath + "BVNetwork.InstantArticles/Views/InstantArticleRssPage/Index.cshtml", model);`

**Comment by pontushagman-zz** [comment]
Actually the view should be in the that location: /modules/BVNetwork.InstantArticles/Views/RssPage/Index.cshtml"

Are you sure you don´t have index.cshtml under that path?

When installing the nuget the index.cshtml should be put there. 
 <file src="Views\InstantArticleRssPage\*.cshtml" target="content\modules\BVNetwork.InstantArticles\Views\RssPage\" />

**Comment by PeterNewsham** [comment]
Thanks for getting back to me on this.

For some reason nuget had added the views to some of the projects within the solution, but not my web project. Moving them about fixed the issue.

Sorry to have wasted your time.
